#!/bin/bash -x
Groups=$(groups)
printsp()
{
	cd $1
	lines=$(( $(ls -la | wc -l)-1 ))
	echo $lines
	ls -la $1 | awk 'NR>1{
	printf substr($0,2,9)
	printf " "
	if($3 == "$USER") printf substr($1,2,3)
	else if ( "$Groups" == "$4" )
		printf substr($1,5,3)" "
	else 
		printf substr($1,8,3) 
				
	print " ", $5, substr($0,1,1), $9}
' | column -t |less -N &
ID=$!
while :
do
	read -n 4
	[[ ${REPLY} =~ .*[0-9]  ]] && Num=${REPLY#[^0-9]} && [ $Num -le $lines ] && kill $ID && break
done
echo $lines
}

open()
{
	fname=$(ls -la | awk -v Num=$(( $Num+1 )) 'NR==$Num {print $9}')
[ -f $fname ] && $($fname) || [ -d $fname ] && printsp $filename
}
printsp $1
open

